Fe1, [24.02.21 14:35]
CREATE DATABASE library;
USE library;
CREATE TABLE book (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(120) NOT NULL,
    info VARCHAR(1000) DEFAULT 'Немає опису',
    publication_date DATE DEFAULT '2018-01-01',
    category VARCHAR(30) NOT NULL UNIQUE,
    isbn varchar(20) NOT NULL UNIQUE,
    pages INT NOT NULL,
    author_name VARCHAR(45) NOT NULL,
    author_surname VARCHAR(45) NOT NULL,
    author_email varchar(50) NOT NULL UNIQUE,
  author_age INT NOT NULL,
    date_of_birth DATE NOT NULL,
  rewards VARCHAR(120) DEFAULT NULL
);
INSERT INTO book(title, info, publication_date, category, isbn, pages, author_name, author_surname, author_email, author_age, date_of_birth, rewards)
VALUES 
(
  '451° по Фаренгейту',
    'Мастер мирового масштаба, совмещающий в литето Рэй Брэдбери. Его увлекательны, но и как филоы детства, чудо приобщения к великой тайне Литературы, щедро раздариваемое читателю, давно вывели Брэдбери на высокую классическую орбиту. Собранные в этой книге произведения - достойное тому подтверждение.',
    '2010-02-10',
    'Роман',
    '123-321-4532-12',
    '120',
    'Лев',
    'Толстой',
    'asdasd@ss.sa',
    '40',
    '1981-01-01',
    'ivamus in lectus at nulla consectetur'
),
(
  'Улисс',
    'Роман "Улисс" великого ирландского писателя Джеймса Джойса, классика и одновременно разрушителя канонов классики, – произведение-эксперимент, знаковое, яркое явление, вершина литературы модернизма ХХ века и главная веха',
    '2000-01-15',
    'Роман',
    '123-321-1142-12',
    '200',
    'Джеймс',
    'Джойс',
    'jo2121132@gmail.com',
    '50',
    '1971-02-05',
    'pellentesque sit amet quis turpis. Proin sed fringilla'
),
(
  'Лоліта',
  'Duis ac interdum ante. Proin massa velit, condimentum et velit vel, rutrum tincidunt massa. Integer ut neque vel magna convallis pharetra vel vitae augue. Aliquam auctor elementum urna sit amet commodo.',
    '2020-04-01',
    'Драма',
    '123-121-4532-12',
    '355',
    'Робет',
    'Майек',
    'rmaik123412@href.src',
    '20',
    '2000-01-05',
    'pellentesque sit amet quis turpis. Proin sed fringilla'
),
(
  'Lorem Inpus',
  'sit amet interdum nulla. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque habitant morbi',
    '2018-02-01',
    'Комедія',
    '553-4224-12',
    '100',
    'Бен',
    'Тен',
    'rm2@href.src',
    '18',
    '2002-04-02',
    'phabitant morbi tristique senectus et netus et malesuada fames'
),
(
  'Lorem Inpus',
  'malesuada fames ac turpis egestas. Pellentesque habitant morbi',
    '2018-02-01',
    'Казка',
    '1111-8888-221',
    '122',
    'Баба',
  'Яга',
    'baba@yaha.com',
    '100',
    '1901-04-02',
    'tristique senectus et netus et malesuada'
),
(
  'Mya knyha',
  'ristique senectus et netus et malesuada fames ac turpis egestas. Nunc feugiat lacinia eleifend. Praesent pharetra pretium ex, nec volutpat odio posuere gravida. Vestibulum sit amet ex rhoncus lorem aliquet consequat id molestie nulla. Morbi porttitor facilisis lacus eu dictum. Phasellus purus tellus, varius sed tincidunt ornare, lacinia et neque. Duis eget mi non dui condimentum feugiat sit amet eget leo. Duis velit erat, fringilla ac metus quis, hend',
    '2018-02-01',
    'Роман',
    '2121-4242-5643-1',
    '500',
    'Боб',
  'Марлі',
    'rasta@faray.com',
    '71',
    '1940-01-01',
    'tristique senectus et netus et malesuada'
),
(
  'BOX',
'Praesent pharetra pretium ex, nec volutpat odio posuere gravida. Vestibulum sit amet ex rhoncus lorem aliquet consequat id molestie nulla. Morbi porttitor facilisis lacus eu dictum. Phasellus purus tellus, varius sed tincidunt ornare, lacinia et neque. Duis eget mi non dui condimentum feugiat sit amet eget leo. Duis velit erat, fringilla ac metus quis, hend',
    '2001-12-23',
    'Спорт',
    '1337-228-1488',
    '5',
    'Vitaliy',
  'Klychko',
    'mer@kyiva.com',
    '40',
    '1981-02-22',
    'Box world chempion!'
),
(
  'Як створити 10 записів у БД за 5хв',
  'Ніяк',
    '2021-02-24'
    'Туторіал',
    '23-2-23-200',
    '1',
    'Кирилов',
  'Олксандр',
    'kyrylov.olexandr@gmail.com',
    '19',
    '2001-04-23',
    'Logos IT academy - java'
),
(
  'Як створити 10 записів у БД за 5хв',
  'Ніяк',
    '2021-02-24',
    'Туторіал',
    '23-2-23-200',
    '1',
    'Кирилов',
  'Олксандр',
    'kyrylov.olexandr@gmail.com',
    '19',
    '2001-04-23',
    'Logos IT academy - java'
),
(
  'The last push',
  'ristique senectulutpat odio posuere gravida. Vestibulum sit amet ex rhoncus lorem aliquet consequat id molestie nulla. Morbi porttitor facilisis lacus eu dictum. Phasellus purus tellus, varius sed tincidunt ornare, lacinia et neque. Duis eget mi non dui condimentum feugiat sit amet eget leo. Duis velit erat, fringilla ac metus quis, hend',
    '1956-03-19',
    'Фантастика',
    '2121-45643-1',
    '332',
    'Еліс',
  'Керли',
    'goo@ooogle.com',
    '99',
    '1922-02-18',
    'Medal of honor'
);